### ISSUE TITLE
RQ2A.210405.005.2021.04.16.04 Beta Test Results

### ISSUE THREAD

**Issue by southwestgit** [GrapheneOS/beta-feedback#1]
Beta Testing Checklist
Date: April 17, 2021
Device: 3a
Build number: RQ2A.210405.005.2021.04.16.04

Recieve incoming calls: Works
Make outgoing phone calls: Yes
Recieve incoming texts: Yes
Send outgoing texts: Yes
Internet connectivity: Yes
Internet browsing: Yes
Vanadium use:
 * Video playback: Yes
 * Renders websites: Yes
Media playback: Yes
PDF Viewer: Not Tested
Alarms/Timer: Yes
Cameras (Front and Rear): Yes
Video: Yes
Microphones: Yes
USB Devices & Peripherals: Yes
File Browsing: Yes
Media Transfer to PC: Not Tested
Application Installs: Yes
Switch Between Profiles: Yes
Log Out Profiles: Yes

Other Notes:
Phone working as expected.

**Comment by bill-in-mtl** [comment]
Beta Testing Checklist

Date: April 18th, 2021
Device: Sunfish(Pixel 4A)
Build number: RQ2A.210405.005.2021.04.16.04

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works
Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works
Renders websites: Works
Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Working
Alarms/Timer: n/a
Cameras (Front and Rear): Works
Video: Works
Handset Microphones: Works
Handset Speakers: Works
Keyboards: Works
File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: n/a
Log Out Profiles: n/a
Seedvault Backups: n/a

**Comment by chris42** [comment]
Date: 18.04.2021
Device: Redfin (Pixel 5)
Build number: RQ2A.210405.005.2021.04.16.04

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works
Internet connectivity: Works
Internet browsing: Works
Vanadium: Works
  ..Renders websites: Works
  ..Media playback: Works
PDF Viewer: Works
Alarms/Timer: Works
Rear and front camera: Works
Microphones: Works
Bluetooth audio: Works
USB Devices & Peripherals: N/A
File Browsing: Works
Media Transfer to PC: Works
Application Installs/Updates: Works
Switch Between Profiles: N/A
Log Out Profiles: N/A
Seedvault Backups: N/A

**Comment by fomijafi** [comment]
Date: April 18th, 2021
Device: Blueline (Pixel 3)
Build number: RQ2A.210305.006.2021.04.16.04

Receive incoming calls: Not Tested
Make outgoing phone calls: works
Receive incoming SMS: Works
Send outgoing SMS: Works
Receive incoming MMS: Works
Send outgoing MMS: Works
Internet connectivity: Works
Internet browsing: Works
Vanadium use

Video playback: Works
Renders websites: several times while browsing vanadium locked up, unable to doing anything on the screen even the power button was unresponsive. Eventually vanadium closed and I lost the tab I had open. This has happened before but not twice in such close proximity.
Password auto-fill: Works
Bookmarks: Works
Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Working
Alarms: working
Timer: working
Cameras (Front and Rear): working but did get one error message during testing front camera: can't connect to the camera once I snapped a photo and attempted to open the photo using the gallery shortcut. I couldn't reproduce.
Video: Works
Handset Microphones: Works
Handset Speakers Works
USB Devices & Peripherals:

USB Mass Storage: not tested
Keyboards: Not Tested
USB Digital Audio Output: not tested
File Browsing:
Media Transfer to PC: not tested
Application Installs: works
Switch Between Profiles: works
Log Out Profiles: Not Tested
Seedvault Backups: not tested


I was travelling and unable to test some things
