### ISSUE TITLE
Version: RQ2A.210405.005.2021.04.16.04

### ISSUE THREAD

**Issue by bill-in-mtl** [GrapheneOS/beta-feedback#10]
Beta Testing Checklist

Date: April 18th, 2021
Device: Sunfish(Pixel 4A)
Build number: RQ2A.210405.005.2021.04.16.04

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works
Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works
Renders websites: Works
Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Working
Alarms/Timer: n/a
Cameras (Front and Rear): Works
Video: Works
Handset Microphones: Works
Handset Speakers: Works
Keyboards: Works
File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: n/a
Log Out Profiles: n/a
Seedvault Backups: n/a

**Comment by thestinger** [comment]
Thanks. https://github.com/GrapheneOS/beta-feedback/issues/1 has feedback from others.

**Comment by thestinger** [comment]
@bill-in-mtl  Could you post it in that thread instead?
