### ISSUE TITLE
RQ2A.210505.002.2021.05.16.04 Beta Test Results

### ISSUE THREAD

**Issue by southwestgit** [GrapheneOS/beta-feedback#14]
Beta Testing Checklist
Date: May 17, 2021
Device: 3a
Build number: RQ2A.210505.002.2021.05.16.04

Receive incoming calls: Yes
Make outgoing phone calls: Yes
Receive incoming texts: Yes
Send outgoing texts: Yes
Internet connectivity: Yes
Internet browsing: Yes
Vanadium use:
 * Video playback: Yes
 * Renders websites: Yes
Media playback: Yes
PDF Viewer: Not Tested
Alarms/Timer: Yes
Cameras (Front and Rear): Yes
Video: Yes
Microphones: Yes
USB Devices & Peripherals: Yes
File Browsing: Works
Media Transfer to PC: Not Tested
Application Installs: Not Tested
Switch Between Profiles: Yes
Log Out Profiles: Yes

Other Notes:
Aurora temp down, could not test app install.

**Comment by thestinger** [comment]
Thanks.
