### ISSUE TITLE
RQ2A.210505.003.2021.05.16.04 Beta Test Results

### ISSUE THREAD

**Issue by Steven0054** [GrapheneOS/beta-feedback#15]
Device: bramble (Pixel 4a 5G)
Build number: RQ2A.210505.003.2021.05.16.04

Receive incoming calls: Works (VoLTE, Legacy, and VoWiFi)
Make outgoing phone calls: Works (VoLTE, Legacy, and VoWiFi)
Receive incoming texts: Works
Send outgoing texts: Works
Receive incoming MMS: Works
Send outgoing MMS: Works
Internet connectivity: Works
Internet browsing: Works
Vanadium use:

Video playback: Works (YouTube, Dailymotion, Viprow)

Renders websites: Works (YouTube, Dailymotion, Viprow, duckduckgo, amazon, https://wiki.codeaurora.org/xwiki/bin/QAEP/release)

Media playback: Works (avi/mkv/aac/flac)
PDF Viewer: Works (3 documents)
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
NFC: Works
Alarms: Works
Timer: Works
Cameras (Front and Rear): Works
Video: Works
Handset Microphones: Works
Handset Speakers: Works
USB Devices & DACs: Works
USB Mass Storage: Works
Keyboards: Partial Working (known USB Keyboard crash bug still applies)

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: Works
Log Out Profiles: Works

Owner Profile Seedvault Backups: Works
Owner Profile Seedvault Restore: Works

Secondary User Profile Seedvault Backups: Works
Secondary User Profile Seedvault Restore: Works

**Comment by thestinger** [comment]
Thanks.
