### ISSUE TITLE
RQ2A.210505.002.2021.05.19.06 Beta Test Results

### ISSUE THREAD

**Issue by akc3n** [GrapheneOS/beta-feedback#16]
Date: May 20th, 2021
Device: Sargo (Pixel 3a)
Build number: RQ2A.210505.002.2021.05.19.06

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming SMS: Works
Send outgoing SMS: Works
Receive incoming MMS: Works
Send outgoing MMS: Works
Data connectivity: Works
Wi-Fi connectivity: Works
Internet browsing: Works
Vanadium use Works

Video playback: Works
Renders websites: Works
Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Works
Alarms: Works
Timer: Works
Cameras (Front and Rear): Works
Video: Works
Handset Microphones: Works
Handset Speakers: Works

USB Devices & Peripherals:

USB Mass Storage: Works
Keyboards: Not Tested
USB Digital Audio Output: Not Tested
File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: Works
Log Out Profiles: Works

Seedvault Backups:

Owner Profile: Not Tested
Secondary Profile: Not Tested
Customization: Not Tested

Other Notes:

Will updated Seedvault backup/restore results soon.
---

EDIT:

Seedvault Backups/Restore:

Owner Profile: Works
Secondary Profile: Works
Customization: Works*

Other Notes:

*Customization: personalized wallpaper did not restore in secondary profile.

App and appdata that was permitted to be backed up and restored worked. 

System Navigation was set to Gesture Navigation prior to update. After the update Gesture Navigation issue with Left/Right swiping would not work. Needed to press a back button where applicable. 

Fix that worked for me: 
Select a different system navigation method and then reactivate Gesture navigation.

**Comment by bill-in-mtl** [comment]
Beta Testing Checklist

Device: Sunfish(Pixel 4A)
Build number: RQ2A.210505.002.2021.05.19.06

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works

Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works
Renders websites: Works

Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Working
Alarms/Timer: n/a

Cameras  (Front and Rear): Works,

Handset Microphones: Works
Handset Speakers: Works

Keyboards: Works

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: n/a
Log Out Profiles: n/a
Seedvault Backups: n/a

**Comment by southwestgit** [comment]
Beta Testing Checklist
Date: May 19, 2021
Device: 3a
Build number: RQ2A.210505.002.2021.05.19.06

Receive incoming calls: Yes
Make outgoing phone calls: Yes
Receive incoming texts: Yes
Send outgoing texts: Yes
Internet connectivity: Yes
Internet browsing: Yes
Vanadium use:
 * Video playback: Yes
 * Renders websites: Yes
Media playback: Yes
PDF Viewer: Not Tested
Alarms/Timer: Yes
Cameras (Front and Rear): Yes
Video: Yes
Microphones: Yes
USB Devices & Peripherals: Yes
File Browsing: Works
Media Transfer to PC: Not Tested
Application Installs: Yes
Switch Between Profiles: Yes
Log Out Profiles: Yes

Other Notes:
None.
