### ISSUE TITLE
RQ3A.210605.005.2021.06.08.06

### ISSUE THREAD

**Issue by magickalsword** [GrapheneOS/beta-feedback#18]
Beta Testing Checklist

Device: Bonita(Pixel 3a XL)
Build number: RQ3A.210605.005.2021.06.08.06

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works

Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works
Renders websites: Works

Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: n/a
PDF Viewer: Works
Alarms/Timer: Works

Cameras (Front and Rear): Works

Handset Microphones: Works
Handset Speakers: Works

Keyboards: Works

File Browsing: Works
Media Transfer to PC: n/a
Application Installs: Works
Switch Between Profiles: Works
Log Out Profiles: Works
Seedvault Backups: n/a

**Comment by bill-in-mtl** [comment]
Beta Testing Checklist

Device: Sunfish(Pixel 4A)
Build number: RQ3A.210605.005.2021.06.08.06

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works

Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works
Renders websites: Works

Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Working
Alarms/Timer: n/a

Cameras  (Front and Rear): Works,

Handset Microphones: Works
Handset Speakers: Works

Keyboards: Works

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: n/a
Log Out Profiles: n/a
Seedvault Backups: n/a

Note: unable to test auto-reboot at this time, so have left default setting to "off"

**Comment by ghost** [comment]
Beta Testing Checklist

Device: Sunfish (Pixel 4A)
Build number: RQ3A.210605.005.2021.06.08.06

Receive incoming calls: ok
Make outgoing phone calls: ok
Receive incoming texts: ok
Send outgoing texts: ok

Internet connectivity: ok
Internet browsing: ok
Vanadium use: ok
Video playback: ok
Renders websites: ok

Media playback: ok
Bluetooth Audio Pairing: ok
Bluetooth Audio Playback: ok
Bluetooth Audio Calling: n/a
PDF Viewer: ok
Alarms/Timer: ok

Cameras (Front and Rear): ok

Handset Microphones: ok
Handset Speakers: ok

Keyboards: ok

File Browsing: ok
Media Transfer to PC: ok

Auto-reboot: ok (tested 1, 2, and 4 hour settings)

**Comment by southwestgit** [comment]
Beta Testing Checklist
Date: June 9, 2021
Device: 3a
Build number: RQ3A.210605.005.2021.06.08.06

Receive incoming calls: Yes
Make outgoing phone calls: Yes
Receive incoming texts: Yes
Send outgoing texts: Yes
Internet connectivity: Yes
Internet browsing: Yes
Vanadium use:
 * Video playback: Yes
 * Renders websites: Yes
Media playback: Yes
PDF Viewer: Not Tested
Alarms/Timer: Yes
Cameras (Front and Rear): Yes
Video: Yes
Microphones: Yes
USB Devices & Peripherals: Yes
File Browsing: Works
Media Transfer to PC: Not Tested
Application Installs: Yes
Switch Between Profiles: Yes
Log Out Profiles: Yes

Other Notes:
Tested Auto reboot, works (1 hr)

**Comment by akc3n** [comment]
Date: June 9th, 2021
Device: Sargo (Pixel 3a)
Build number: RQ3A.210605.005.2021.06.08.06

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming SMS: Works
Send outgoing SMS: Works
Receive incoming MMS: Works
Send outgoing MMS: Works
Data connectivity: Works
Wi-Fi connectivity: Works
Internet browsing: Works
Vanadium use Works

Video playback: Works
Renders websites: Works
Media playback: Works
Bluetooth Audio Pairing: Not Tested
Bluetooth Audio Playback: Not Tested
Bluetooth Audio Calling: Not Tested
PDF Viewer: Works
Alarms: Not Tested
Timer: Not Tested
Cameras (Front and Rear): Works
Video: Works 
Handset Microphones: Works
Handset Speakers: Works
USB Devices & Peripherals:

USB Mass Storage: Works
Keyboards: Not Tested
USB Digital Audio Output: Not Tested
File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: Works
Log Out Profiles: Works

Seedvault Backups:

Owner Profile: Works
Secondary Profile: Works
Customization: Works

Auto Reboot: Not Tested

Other Notes:
Haven't tested Auto Reboot yet, will do so after work today. 

EDIT:
Auto Reboot: Works

**Comment by Metr0pl3x** [comment]
Date: June 10th, 2021
Device: Blueline (Pixel 3)
Build number: RQ3A.210605.005.2021.06.08.06

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming SMS: Works
Send outgoing SMS: Works
Receive incoming MMS: Works
Send outgoing MMS: Not Tested (Spending Cap)
Data connectivity: Works
Wi-Fi connectivity: Works
Hotspot: Works
Hotspot set in owner profile logged into other user: Works
Internet browsing: Works
Vanadium use Works

Video playback: Works
Renders websites: Works
Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Track Info: Works (Spotify and Newpipe tested)
Bluetooth Audio Calling: Works
PDF Viewer: Works
Alarms: Works
Alarm set in owner profile logged into other user: Works
Timer: Works
Timer set in owner profile logged into other user: Works
Cameras (Front and Rear): Works
Video: Works
Handset Microphones: Works
Handset Speakers: Works

USB Devices & Peripherals:
USB Mass Storage: Works
Keyboards: Not Tested
USB Digital Audio Output: Not Tested
File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: Works
Log Out/End Session Profiles: Works

Seedvault Backups: Untested

Owner Profile: Works
Secondary Profile: Works
Customization: Works*

Auto Reboot: Works (1 Hour)
Auto Reboot set from Owner Profile while logged into different user: Works (1 Hour)

Indicators: Working

Other Notes:
Switching to a brand new user turned off mobile data on owner profile, incoming calls worked even when toggle for calls/sms left off for new user, if calling through owner profile, contact details weren't passed through to secondary profile.
*When auto rebooted from different user that users style persisted over to the owner profile when unlocked.
