### ISSUE TITLE
RQ3A.210605.005.2021.06.08.06 Auto Shutdown Test

### ISSUE THREAD

**Issue by Peter-Easton** [GrapheneOS/beta-feedback#19]
**Date:** June 09, 2021
**Device:** Flame (Pixel 4)
**Build number:** RQ3A.210605.005.2021.06.08.06

### Procedure
The phone was switched on and unlocked to the owner profile, and the setting in **Settings -> Security -> Auto Reboot** changed to **1 hour*. For the next 2 hours, the phone was locked and unlocked, and used as normal for various tasks including texting, calls, internet browsing, and running apps. Internet access was allowed during this time, during both Wi Fi and Cellular Service. No other profile was in service at the time. 

### Expected Outcome
The phone would remain running without shutting down, so long as the phone was not left unattended and time between unlock exceeded more than 1 hour.

### Observed Outcome
The phone worked fine. No deviations from expected outcome. 

### Procedure
The phone was left with its settings from the previous stage. The power button was tapped to return the phone to its lock screen. To avoid interference via the facial unlock system, the phone was placed an arms' length on a desk. At approximately halfway through the test, the phone was checked by tapping the power button once to wake the screen, but not unlocked. This continued for one hour. After an hour had passed, the phone was checked.

### Expected Outcome
The phone would be locked, and display a prompt to show that the phone had rebooted and was now expecting a password authentication. The facial recognition sensor would be inactivated.

### Observed Outcome
As expected. The phone worked fine. No deviations from expected outcome.

## Conclusions
The auto-reboot function is working as expected.

**Comment by thestinger** [comment]
Thanks for the thorough testing!
