### ISSUE TITLE
RQ3A.210605.005.2021.06.09.13

### ISSUE THREAD

**Issue by magickalsword** [GrapheneOS/beta-feedback#20]
Beta Testing Checklist

Device: Bonita(Pixel 3a XL)
Build number: RQ3A.210605.005.2021.06.09.13

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works

Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works
Renders websites: Works

Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Works
Alarms/Timer: Works

Cameras (Front and Rear): Works

Handset Microphones: Works
Handset Speakers: Works

Keyboards: Works

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: Works
Log Out Profiles: Works
Seedvault Backups: n/a

**Comment by thestinger** [comment]
Thanks.

**Comment by flawedworld** [comment]
Beta Testing Checklist

Device: redfin (Pixel 5)
Build number: RQ3A.210605.005.2021.06.09.13

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works

Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works
Renders websites: Works

Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Works
Alarms/Timer: untested

Cameras (Front and Rear): Works

Headset Microphones: untested
Headset Speakers: untested

Keyboards: Works (affected by known keyboard crash bug)
Mice: Works (affected by known keyboard crash bug)

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: Works
Log Out Profiles: Works
Seedvault Backups: untested

Known bug: Some lag time when pressing power button to awake device, this appears to be an upstream kernel issue.

**Comment by ghost** [comment]
Beta Testing Checklist
Notes: Resetted the device before updating to beta. Device does not have a SIM card or any mobile network connectivity.

Device: redfin (Pixel 5)
Build number: RQ3A.210605.005.2021.06.09.13

Receive incoming calls: untested
Make outgoing phone calls: untested
Receive incoming texts: untested
Send outgoing texts: untested

Internet connectivity: Works (tested with Wi-Fi only)
Internet browsing: Works
Vanadium use Works
Video playback: Works
Renders websites: Works

Media playback: Works
Bluetooth Audio Pairing: untested
Bluetooth Audio Playback: untested
Bluetooth Audio Calling: untested
PDF Viewer: Works
Alarms/Timer: Works

Cameras (Front and Rear): Works

Headset Microphones: untested
Headset Speakers: Works

Keyboards: Works (affected by known keyboard crash bug)
Mice: Works (affected by known keyboard crash bug)

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: Works
Log Out Profiles: Works
Seedvault Backups: See [1]

(Extras)
Adding Accounts (in Settings): See [2]
Auditor Remote Verification: Works
Gallery App: See [3]
Wi-Fi hotspot: Works

[1] When selecting Nextcloud backup location without the Nextcloud app installed or any play/app store of somekind (Aurora Store or F-Droid for example), it will try to open an app store but fail to, bringing you back to the area where you select a backup location with no message or anything.

[2] Selecting  "Add account" does nothing when there are no apps available to add accounts to. Maybe a dialog to let the user know there are no apps?

[3] Opening the Gallery app, clicking the 3 dots in top right, and going to Settings brings you to a black screen with the Gallery app and nothing else. No settings or anything.

**Comment by Steven0054** [comment]
Device: bramble (Pixel 4a 5G)
Build number: RQ3A.210605.005.2021.06.09.13

Receive incoming calls: Works (VoLTE, Legacy, and VoWiFi)
Make outgoing phone calls: Works (VoLTE, Legacy, and VoWiFi)
Receive incoming texts: Works
Send outgoing texts: Works

Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works (YouTube, Dailymotion, Viprow)
Renders websites: Works (YouTube, Dailymotion, Viprow, duckduckgo, amazon, https://wiki.codeaurora.org/xwiki/bin/QAEP/release)

Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Works (3 documents)
Alarms/Timer: Works (tested and not interfering with auto-reboot)

Cameras (Front and Rear): Works

Headset Microphones: Works
Headset Speakers: Works

USB Devices & DACs: Works
USB Mass Storage: Works
Keyboards: Partial Working (known USB Keyboard crash bug still applies)

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: Works
Log Out Profiles: Works

Owner Profile Seedvault Backups: Works
Owner Profile Seedvault Restore: Works

Secondary User Profile Seedvault Backups: Works
Secondary User Profile Seedvault Restore: Works

**Comment by kapriworn** [comment]
Device: bramble (Pixel 4a 5G)
Build number: RQ3A.210605.005.2021.06.09.13

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works

Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works 
Renders websites: Works

Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
- Tested multiple headsets, IEMs, speakers.


PDF Viewer: Works 
Alarms/Timer: Works 
Auto Reboot: Works

Cameras (Front and Rear): Works

Headset Microphones: Works
Headset Speakers: Works

USB Devices: Works
USB Mass Storage: Works
Keyboards: Works

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: Works
Log Out Profiles: Works

**Comment by mrxx0** [comment]
Device: Sunfish (Pixel 4a)
Build number: RQ3A.210605.005.2021.06.09.13

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works

Internet connectivity: Works
Internet browsing: Works
Vanadium use : Works
Video playback: Works
Renders websites: Works

Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works

Tested 2 headphones.
NFC : Works

PDF Viewer: Works
Alarms/Timer: Works
Auto Reboot: Works

Cameras (Front and Rear): Works

Headset Microphones: Works
Headset Speakers: Works

USB Devices: Works
USB Mass Storage: Works
Keyboards: Works

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: Works
Log Out Profiles: Works
