### ISSUE TITLE
RQ3A.210605.005.2021.06.20.20 Beta Test

### ISSUE THREAD

**Issue by southwestgit** [GrapheneOS/beta-feedback#21]
Beta Testing Checklist
Date: June 22, 2021
Device: 3a
Build number: RQ3A.210605.005.2021.06.20.20

Receive incoming calls: Yes
Make outgoing phone calls: Yes
Receive incoming texts: Yes
Send outgoing texts: Yes
Internet connectivity: Yes
Internet browsing: Yes
Vanadium use:
 * Video playback: Yes
 * Renders websites: Yes
Media playback: Yes
PDF Viewer: Not Tested
Alarms/Timer: Yes
Cameras (Front and Rear): Yes
Video: Yes
Microphones: Yes
USB Devices & Peripherals: Yes
File Browsing: Works
Media Transfer to PC: Not Tested
Application Installs: Yes
Switch Between Profiles: Yes
Log Out Profiles: Yes

Other Notes:
Was not able to test IPv6

**Comment by akc3n** [comment]
## SETUP
---

**Device:** Sargo (Pixel 3a)  
**Release Version:** RQ3A.210605.005.2021.06.20.20  
**Date:** Tuesday, June 22nd, 2021  

---

## BETA TEST CHECKLIST

**Receive incoming calls:** Works  
**Make outgoing phone calls:** Works  
**Receive incoming texts:** Works  
**Send outgoing texts:** Works  

**Internet connectivity:** Works  
**Internet browsing:** Works  
**Vanadium Use:** Works  
**Video playback:** Works  
**Renders websites:** Works  

**Media playback:** Works  
**Bluetooth Audio Pairing:** Works  
**Bluetooth Audio Playback:** Works  
**Bluetooth Audio Calling:** Works  
**PDF Viewer:** Works  
**Alarms/Timer**: Works  

**Cameras (Front and Rear):** Works  
**Camera & Mic Indicators:** Works

**Headset Microphones:** Works  
**Headset Speakers:** Works  

**File Browsing:** Works  
**Media Transfer to PC:** Works  
**Application Installs:** Works  
**Switch Between Profiles:** Works  
**Log Out Profiles:** Works  

**SEEDVAULT**  
**Owner Backup:** Works  
**Owner Restore:** Works  
**Secondary Backup:** Works  
**Secondary Restore:** Works  
**Customization Backup/Restore:** Works

**AUTO-REBOOT**  
**Owner:** Works  
**Secondary:** Works  

**IPv6 CONNECTIVITY**  
**Wi-Fi:** Works  
**Mobile Data:** Untested (no data plan on borrowed sim card)  

---
## NOTES

I've noticed that after updating there is an issue with system gesture navigation. Even though it is set as the default, I still manually have to go to `Settings`->`System`->`Gestures`->`System navigation` and select either `2-button navigation` or `3-button navigation`, then have to reselect `Gesture Navigation` in order fully enable swipe capabilities.
