### ISSUE TITLE
RQ3A.210705.001.2021.07.19.18 Beta Test Results

### ISSUE THREAD

**Issue by Jawshy** [GrapheneOS/beta-feedback#23]
**Date:** 21 July 2021
**Device:** Bonito (Pixel 3a XL)
**Build number:** RQ3A.210705.001.2021.07.19.18

**Receive incoming calls:** Working
**Make outgoing phone calls:** Working
**Receive incoming SMS:** Working
**Send outgoing SMS:** Working
**Receive incoming MMS:** Not tested
**Send outgoing MMS:** Not tested
**Data connectivity:** Working
**Wi-Fi connectivity:** Working
**Internet browsing:** Working
**Vanadium use** 
* Video playback: Working
* Renders websites: Working

**Media playback:** Working
**Bluetooth Audio Pairing:** Not tested
**Bluetooth Audio Playback:** Not tested
**Bluetooth Audio Calling:** Not tested
**PDF Viewer:** Working
**Alarms:** Working
**Timer:** Working
**Cameras (Front and Rear):** Both working
**Video:** Working
**Handset Microphones:** Working
**Handset Speakers:** Working
**USB Devices & Peripherals:**
* USB Mass Storage: Working
* Keyboards: Not tested
* USB Digital Audio Output: Not tested

**File Browsing:** Working
**Media Transfer to PC:** Working
**Application Installs:** Working, able to update app via Aurora Store
**Switch Between Profiles:** Working
**Log Out Profiles:** Working
**Seedvault Backups:**
* **Owner Profile**: Backed up but not restored
* **Secondary Profile**: Not tested

**Customization:** 

**Other Notes:**
When phone was rebooted after update I was not prompted for my SIM card unlock PIN. Wi-Fi doesn't turn on but silently fails (no error). Phone calls don't work and prompt message 'mobile network not available'. Mobile data can't be turned on and has message 'no SIM card'. Removing and inserting SIM card again doesn't fix. Tested on primary (owner) profile. 

EDIT: Addressed in https://app.element.io/#/room/#testing:grapheneos.org 'it was found to be a bad build due to bad linux USB drivers' - June V. Sideload https://releases.grapheneos.org/bonito-ota_update-2021.07.19.18.zip

EDIT 2: Updated checklist.

**Comment by thestinger** [comment]
For anyone else running into this make sure to sideload https://releases.grapheneos.org/bonito-factory-2021.07.19.18.zip

**Comment by thestinger** [comment]
For anyone else running into this issue with the initially uploaded build make sure to sideload https://releases.grapheneos.org/bonito-ota_update-2021.07.19.18.zip which fixes it.
