### ISSUE TITLE
RQ3A.211001.001.2021100606 (Alpha Release)

### ISSUE THREAD

**Issue by Peter-Easton** [GrapheneOS/beta-feedback#24]
# Device Information
**Date:** October 7th 2021
**Device:** Flame (Pixel 4)
**Build number:** RQ3A.211001.001.2021100606

## Core Functionality
**Receive incoming calls:** Works
**Make outgoing phone calls:** Works
**Receive incoming SMS:** Works
**Send outgoing SMS:** Works
**Receive incoming MMS:** Works
**Send outgoing MMS:** Works
**Data connectivity:** Works
**Wi-Fi connectivity:** Works
**Internet browsing:** Works
**Vanadium use** 
 * Video playback: Works
 * Renders websites: Works

## Sound and Devices
**Media playback:** Works
**Bluetooth Audio Pairing:** Works
**Bluetooth Audio Playback:** Works
**Bluetooth Audio Calling:** Works
**PDF Viewer:** Works
**Alarms:** Not Tested
**Timer:** Not Tested
**Cameras (Front and Rear):** Works
**Video:** Works 
**Handset Microphones:** Works
**Handset Speakers:** Works
**USB Mass Storage:** Works
**USB Keyboards:** Works
**USB Digital Audio Output:** Works

## Files
**File Browsing:** Works
**Media Transfer to PC:** Works
**Application Installs:** Works
**Switch Between Profiles:** Works 
**Log Out Profiles:** Works
**Auditor Local Pairing:** Works

## Sandboxed Play Services
**Sandboxed Play Services**
**Banking App:** Works
**Google Camera App:** Works
**Push Notifications:** Not tested

## Seedvault Backups
 * **Owner Profile**: Works
 * **Secondary Profile**: Not Tested

## Miscellaneous
**Customization:** Works.

**Other Notes:**
No breakages or broken features observed.

**Comment by thestinger** [comment]
Thanks.
