### ISSUE TITLE
SQ1A.211205.008.2021120717 Beta Test

### ISSUE THREAD

**Issue by Peter-Easton** [GrapheneOS/beta-feedback#26]
# Device Information
**Date:** December 9th, 2021
**Device:** Flame (Pixel 4)
**Build number:** SQ1A.211205.008.2021120717

## Core Functionality
**Receive incoming calls:** Works
**Make outgoing phone calls:** Works
**Receive incoming SMS:** Works
**Send outgoing SMS:** Works
**Receive incoming MMS:** Works
**Send outgoing MMS:** Works
**Data connectivity:** Works
**Wi-Fi connectivity:** Works 
**Internet browsing:** Works
**Vanadium use** 
 * Video playback: Works
 * Renders websites: Works
 * Downloads: Works
 * General Browsing: Works

## Sound and Devices
**Media playback:** Works
**Bluetooth Audio Pairing:** Works
**Bluetooth Audio Playback:** Works
**Bluetooth Audio Calling:** Works
**PDF Viewer:** Works
**Alarms:** Not Tested
**Timer:** Not Tested
**Cameras (Front and Rear):** Works
**Video:** Works
**Handset Microphones:** Works
**Handset Speakers:** Works
**USB Mass Storage:** Works 
**USB Keyboards:** Works
**USB Digital Audio Output:** Works

## Files
**File Browsing:** Works
**Media Transfer to PC:** Works
**Application Installs:** Works
**Switch Between Profiles:** Works
**Log Out Profiles:** Works
**Auditor Local Pairing:** Works

## Sandboxed Play Services
**Sandboxed Play Services:** Works
**Google Camera App:** Works
**Push Notifications:** Works
**Banking Apps (Not requiring safety net):** Works

## Seedvault Backups
 * **Owner Profile**: Works
 * **Secondary Profile**: Not Tested

**Upstream:** When taking a backup with "Backup Files" selected to a USB Drive, Seedvault will report that a backup has failed in the notifications bar, but when investigated in the "Backup Status" window, reports a successful backup. It will indicate that Seedvault is backing up files, but then stop at 100% and hang, and the notification bubble will not disappear until the phone has been rebooted. This issue may be for upstream. 

**Other Notes:**
Everything seems to be in good working order.

**Comment by thestinger** [comment]
Thanks.
