### ISSUE TITLE
Raven SQ1D.211205.017.2021121421 Experimental Release Test Results

### ISSUE THREAD

**Issue by Peter-Easton** [GrapheneOS/beta-feedback#27]
# Device Information
**Date:** December 15th, 2021
**Device:** Raven (Pixel 6 Pro)
**Build number:** SQ1D.211205.017.2021121421

## Core Functionality
**Receive incoming calls:** Works
**Make outgoing phone calls:** Works
**Receive incoming SMS:** Works
**Send outgoing SMS:** Works
**Receive incoming MMS:** Works
**Send outgoing MMS:** Works
**Data connectivity:** Works
**Wi-Fi connectivity:** Works 
**Internet browsing:** Works
**Location Services:** Works 
**Biometrics Login (In-Screen Fingerprint Scanner):** Works
**Vanadium use** 
 * Video playback: Works
 * Renders websites: Works
 * Downloads: Works
 * General Browsing: Works

## Sound and Devices
**Media playback:** Works
**Bluetooth Audio Pairing:** Works
**Bluetooth Audio Playback:** Works
**Bluetooth Audio Calling:** Works
**PDF Viewer:** Works
**Alarms:** Not Tested
**Timer:** Not Tested
**Cameras (Front and Rear):** Works
**Video:** Works
**Handset Microphones:** Works
**Handset Speakers:** Works
**USB Mass Storage:** Works 
**USB Keyboards:** Not Tested
**USB Digital Audio Output:** Works

## Files
**File Browsing:** Works
**Media Transfer to PC:** Works
**Application Installs:** Works
**Switch Between Profiles:** Works
**Log Out Profiles:** Works
**Auditor Local Pairing:** Works

## Sandboxed Play Services
**Sandboxed Play Services:** Not Tested
**Google Camera App:** Not Tested
**Push Notifications:** Not Tested
**Banking Apps (Not requiring safety net):** Not Tested

## Seedvault Backups
**Anything in this section is upstream!**
**Owner Profile**: Works (See Below)
**Secondary Profile**: Not tested

* **Upstream Issue:** When taking a backup with "Backup Files" selected to a USB Drive, Seedvault will report that a backup has failed in the notifications bar, but when investigated in the "Backup Status" window, reports a successful backup. It will indicate that Seedvault is backing up files, but then stop at 100% and hang, and the notification bubble will not disappear until the phone has been rebooted. This issue may be for upstream. 
* **Upstream Issue:** If files are selected to be included in the backup, this causes the backup to be incomplete, and prevent it from being restored on the destination device. A backup was taken from a Pixel 4 and restored to a Pixel 6. Although the word lists were double-checked and triple checked, the backup could not be restored, with the device returning an error about either the seed being incorrect or the backup not being found. When file backup was switched off and a new backup taken, the backup completed successfully and was successfully restored on the new device. One file that was particularly troublesome for the USB drive to accomodate was a large ~6GB file containing uncompressible data which was selected for backup, and could not be copied off the phone using.  **Conclusions:** File restoration in SeedVault is not fully stable at the time of writing.

## Changes to the permission model
Testing Signal 5.27.13 when Network Permission was revoked produced the desired effect of the app continuing to function offline, rather than crash when Network Permission was denied. The app functioned normally once Network Permission was restored. **Conclusions:** The changes to the new Network Permission model are working as they are intended.

## Other Notes
Everything seems to be in good working order. 

I did not test Sandboxed Play Services this time due to some time constraints.

**Comment by thestinger** [comment]
Thanks.
